openapi: 3.0.0
info:
  version: 1.0.0
  title: Custom
  description: "These are some extra routes for rocket.chat because open api files from rocket.chat has some missing stuff"
tags:
  - name: Custom
servers:
  - url: 'https://apiexplorer.support.rocket.chat'
paths:
  /api/v1/login:
    post:
      tags:
        - Custom
      summary: Login with ServiceName and Token
      description: -|
        Added because authentication with serviceName and accessToken is missing
      operationId: post-api-v1-login
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceName:
                  type: string
                  description: Name of the authentication service
                  example: keycloak
                accessToken:
                  type: string
                  description: Access token generated by authentication service
                  example: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiw...
                expiresIn:
                  type: integer
                  description: Expiretime of access token
                  example: 300
            examples:
              Example:
                value:
                  serviceName: keycloak
                  accessToken: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiw
                  expiresIn: 300
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      authToken:
                        type: string
                      userId:
                        type: string
                      me:
                        type: object
                        properties:
                          _id:
                            type: string
                          name:
                            type: string
                          emails:
                            type: array
                            items:
                              type: object
                              properties:
                                address:
                                  type: string
                                verified:
                                  type: boolean
                          status:
                            type: string
                          statusConnection:
                            type: string
                          username:
                            type: string
                          utcOffset:
                            type: integer
                          active:
                            type: boolean
                          roles:
                            type: array
                            items:
                              type: string
                          settings:
                            type: object
                            properties:
                              preferences:
                                type: object
                          avatarUrl:
                            type: string
                x-examples:
                  Example:
                    status: success
                    data:
                      authToken: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq
                      userId: aobEdbYhXfu5hkeqG
                      me:
                        _id: aYjNnig8BEAWeQzMh
                        name: Rocket Cat
                        emails:
                          - address: rocket.cat@rocket.chat
                            verified: false
                        status: offline
                        statusConnection: offline
                        username: rocket.cat
                        utcOffset: -3
                        active: true
                        roles:
                          - admin
                        settings:
                          preferences: {}
                        avatarUrl: 'http://localhost:3000/avatar/test'
              examples:
                Login successful:
                  value:
                    status: success
                    data:
                      authToken: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq
                      userId: aobEdbYhXfu5hkeqG
                      me:
                        _id: aYjNnig8BEAWeQzMh
                        name: Rocket Cat
                        emails:
                          - address: rocket.cat@rocket.chat
                            verified: false
                        status: offline
                        statusConnection: offline
                        username: rocket.cat
                        utcOffset: -3
                        active: true
                        roles:
                          - admin
                        settings:
                          preferences: {}
                        avatarUrl: 'http://localhost:3000/avatar/test'
  /api/v1/chat.sendMessage:
    post:
      tags:
        - Custom
      summary: Send Message
      description: |-
        Overwritten because property t is wrong documented
      operationId: post-api-v1-chat.sendMessage
      parameters:
        - $ref: '#/components/parameters/Auth-Token'
        - $ref: '#/components/parameters/UserId'
      requestBody:
        description: |-
          **Some important things to note about the `previewUrls` parameter include:**
          * If the `previewUrls` array is empty, no URL will be previewed.
          * If the `previewUrls` parameter isn't sent, all URLs (up to a maximum of five external URLs) will be previewed.
          * If the message contains attachments or quotes, no URL is previewed.
          * Internal URLs are not considered in the `previewUrls` array.
          * A maximum of five external URLs is previewed  per message. If there are more than 5 external URLs, no URL is previewed.
          > URLs that include the same text as the <a href='https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/general#general-settings' target='_blank'>**Site URL**</a> are referred to as Internal URLs.
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  properties:
                    t:
                      type: string
                      description: The message type e.g. e2e
                    rid:
                      type: string
                      description: The room ID where the message is to be sent.
                    msg:
                      type: string
                      description: 'The message text to send, it is optional because of attachments.'
                    alias:
                      type: string
                      description: 'This will cause the message''s name to appear as the given alias, but your username will still be displayed. Requires the `impersonate-other-user` permission'
                    emoji:
                      type: string
                      description: 'If provided, the avatar will be displayed as the emoji. '
                    avatar:
                      type: string
                      description: 'If provided, the avatar will be displayed as the provided image url. Requires the  `impersonate-other-user` permission.'
                    attachments:
                      type: array
                      description: |-
                        The attachment is an array of objects with any of the following properties. One attachment can have many sections, including:
                        * General
                        * Author Information
                        * Title Information
                        * Image
                        * Audio
                        * Video
                        * Table/Fields
                      items:
                        type: object
                        properties:
                          audio_url:
                            type: string
                            description: |-
                              Audio file to attach. See <a href='https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio' target='_blank'>HTML audio element</a> for information.
                          author_icon:
                            type: string
                            description: Displays a tiny icon to the left of the author's name.
                          author_link:
                            type: string
                            description: Providing this makes the author name clickable and points to this link.
                          author_name:
                            type: string
                            description: Name of the author.
                          collapsed:
                            type: boolean
                            description: 'Causes the image, audio, and video sections to be displayed as collapsed when set to true.'
                          color:
                            type: string
                            description: |-
                              See <a href='https://developer.mozilla.org/en-US/docs/Web/CSS/background-color' target='_blank'>background-css</a> for the supported format.
                          fields:
                            type: array
                            items:
                              type: object
                              properties:
                                short:
                                  type: boolean
                                  description: Whether this field should be a short field.
                                title:
                                  type: string
                                  description: The title of this field.
                                value:
                                  type: string
                                  description: 'The value of this field, displayed underneath the title value.'
                              required:
                                - title
                                - value
                          image_url:
                            type: string
                            description: 'The image to display, will be big and easy to see.'
                          message_link:
                            type: string
                            description: 'Only applicable if the `ts` parameter is provided, as it makes the time clickable to this link.'
                          text:
                            type: string
                            description: 'The text to display for this attachment, it is different than the message''s text.'
                          thumb_url:
                            type: string
                            description: 'An image that displays to the left of the text, looks better when this is relatively small.'
                          title:
                            type: string
                            description: 'Title to display for this attachment, displays under the author.'
                          title_link:
                            type: string
                            description: 'Providing this makes the title clickable, pointing to this link.'
                          title_link_download:
                            type: boolean
                            description: 'When this is true, a download icon appears and clicking this saves the link to file.'
                          ts:
                            type: string
                            description: Displays the time next to the text portion.
                          video_url:
                            type: string
                            description: |-
                              Video file to attach. See the <a href='https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video' target='blank'>HTML video element</a> for information.
                    tmid:
                      type: string
                      description: The message ID to create a thread.
                    tshow:
                      type: string
                      description: Used when replying in a thread. Message will be sent in channel also if value is true
                    blocks:
                      type: object
                      description: |-
                        A message block is an array of objects with any of the following properties. Blocks can have many sections:
                        - type
                        - text
                        - fields
                    customFields:
                      type: object
                      description: |-
                        You can add custom fields for messages. For example, set priorities for messages.
                        
                        You must enable this option and define the validation in the workspace settings. See the <a href='https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/message' target='_blank'>Message</a> settings for further information.
                      example: { "priority": "high" }
                  required:
                    - rid
                'previewUrls ':
                  type: array
                  description: An array to define which URL previews should be retrieved from each message.
                  items:
                    type: string
            examples:
              Message with Attachments:
                value:
                  message:
                    rid: Xnb2kLD2Pnhdwe3RH
                    msg: Sample message
                    alias: Gruggy
                    emoji: ':smirk:'
                    avatar: 'http://res.guggy.com/logo_128.png'
                    attachments:
                      - color: '#ff0000'
                        text: Yay for gruggy!
                        ts: '2016-12-09T16:53:06.761Z'
                        thumb_url: 'http://res.guggy.com/logo_128.png'
                        message_link: 'https://google.com'
                        collapsed: false
                        author_name: Bradley Hilton
                        author_link: 'https://rocket.chat/'
                        author_icon: 'https://avatars.githubusercontent.com/u/850391?v=3'
                        title: Attachment Example
                        title_link: 'https://youtube.com'
                        title_link_download: true
                        image_url: 'http://res.guggy.com/logo_128.png'
                        audio_url: 'http://www.w3schools.com/tags/horse.mp3'
                        video_url: 'http://www.w3schools.com/tags/movie.mp4'
                        fields:
                          - short: true
                            title: Test
                            value: Testing out something or other
                          - short: true
                            title: Another Test
                            value: '[Link](https://google.com/) something and this and that.'
              Message with Blocks:
                value:
                  message:
                    rid: GENERAL
                    blocks:
                      - type: section
                        text:
                          type: mrkdwn
                          text: '*Text example* Normal message `code` here'
                      - type: divider
                      - type: section
                        fields:
                          - type: mrkdwn
                            text: '*Field 1*'
                          - type: mrkdwn
                            text: Field 2
              Message with PreviewURLs:
                value:
                  message:
                    rid: 64f0f82c2c26843a68c1f7ba
                    msg: 'This is a list of links! https://google.com https://hola.org/ https://www.usepayday.com/ https://www.getbumpa.com/ https://www.atlassian.com/software/jira http://localhost:3000/'
                  previewUrls:
                    - 'https://google.com'
                    - 'http://localhost:3000/'
                    - 'https://hola.org/'
                    - 'https://www.usepayday.com/'
                    - 'https://www.getbumpa.com/'
                    - 'https://www.atlassian.com/software/jira'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      rid:
                        type: string
                      msg:
                        type: string
                      ts:
                        type: string
                      u:
                        type: object
                        properties:
                          _id:
                            type: string
                          username:
                            type: string
                          name:
                            type: string
                      unread:
                        type: boolean
                      mentions:
                        type: array
                        items:
                          type: object
                      channels:
                        type: array
                        items:
                          type: object
                      _updatedAt:
                        type: string
                      _id:
                        type: string
                  success:
                    type: boolean
              examples:
                Example 1:
                  value:
                    message:
                      rid: GENERAL
                      msg: '123456789'
                      ts: '2018-03-01T18:02:26.825Z'
                      u:
                        _id: i5FdM4ssFgAcQP62k
                        username: rocket.cat
                        name: test
                      unread: true
                      mentions: [ ]
                      channels: [ ]
                      _updatedAt: '2018-03-01T18:02:26.828Z'
                      _id: LnCSJxxNkCy6K9X8X
                    success: true
        '401':
          $ref: '#/components/responses/authorizationError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  errorType:
                    type: string
              examples:
                Example 1:
                  value:
                    success: false
                    error: 'The "message" parameter must be provided. [error-invalid-params]'
                    errorType: error-invalid-params
                Example 2:
                  value:
                    success: false
                    error: The 'rid' property on the message object is missing.
                Example 3:
                  value:
                    success: false
                    error: error-invalid-room
  /api/v1/chat.getMessage:
    get:
      tags:
        - Custom
      summary: Get Message
      description: |-
        Overwritten because repsonse is wrong documented
      operationId: get-api-v1-chat.getMessage
      parameters:
        - $ref: '#/components/parameters/Auth-Token'
        - $ref: '#/components/parameters/UserId'
        - name: msgId
          in: query
          description: The message ID.
          required: true
          schema:
            type: string
          example: 7aDSXtjMA3KPLxLjt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      _id:
                        type: string
                      rid:
                        type: string
                      msg:
                        type: string
                      alias:
                        type: string
                      ts:
                        type: string
                      u:
                        type: object
                        properties:
                          _id:
                            type: string
                          username:
                            type: string
                          name:
                            type: string
                      _updatedAt:
                        type: string
                      reactions:
                        type: object
                        properties:
                          ':frowning2:':
                            type: object
                            properties:
                              usernames:
                                type: array
                                items:
                                  type: string
                      mentions:
                        type: array
                        items:
                          type: object
                      channels:
                        type: array
                        items:
                          type: object
                      starred:
                        type: object
                        properties:
                          _id:
                            type: string
                      t:
                        type: string
                      groupable:
                        type: boolean
                  success:
                    type: boolean
              examples:
                Success:
                  value:
                    message:
                      _id: CeXwh5eBbdrtvnqG6
                      rid: agh2Sucgb54RQ8dDo
                      msg: s
                      ts: '2018-10-05T13:48:21.616Z'
                      u:
                        _id: KPkEYwKKBKZnEEPpt
                        username: marc.pow
                        name: Marc Pow
                      _updatedAt: '2018-10-05T13:48:49.535Z'
                      reactions:
                        ':frowning2:':
                          usernames:
                            - marcos.defendi
                      mentions: [ ]
                      channels: [ ]
                      starred:
                        _id: KPkEYwKKBKZnEEPpt
                    count: 2
                    offset: 0
                    total: 2
                    success: true
        '401':
          $ref: '#/components/responses/authorizationError'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
              examples:
                Example 1:
                  value:
                    success: false
                    error: The "msgId" query parameter must be provided.

  /api/v1/settings/{_id}:
    parameters:
      - schema:
          type: string
        name: _id
        in: path
        required: true
        description: The unique ID of the setting that you want to update or fetch.
    post:
      summary: Update Setting
      tags:
        - Custom
      responses:
        '200':
          $ref: '#/components/responses/trueSuccess'
        '401':
          $ref: '#/components/responses/authorizationError'
      operationId: post-api-v1-settings-_id
      description: |-
        Permission required: `edit-privileged-setting`

        The `_id` of a setting is the first argument of the `RocketChat.settings.add` method used in `Rocket.Chat/packages/rocketchat-lib/server/startup/settings.js` (among other files). 

        For example, the following code in `settings.js` file:
          ```json
          this.add('Accounts_AllowAnonymousRead', false, {
            type: 'boolean',
            public: true  });
          ```
          This means that the setting labeled `Allow anonymous read` in the section `Accounts` has `_id` equal to `Accounts_AllowAnonymousRead`. The second argument is the default value (false). The third argument specifies the variable's type and whether it is public, hidden, and so on. 

          To set a color, you can send:
          ```json
          { value: '<color-code>',
            editor: 'color' }
          ```

          And also to trigger a action-button, use:
          ```json
          { execute: true }
          ```
          ### Changelog
          | Version      | Description |
          | ---------------- | ------------|
          |0.65.0            | Added option to set a color and trigger an action       |
          |0.42.0            | Added       |
      parameters:
        - $ref: '#/components/parameters/X-User-Id'
        - $ref: '#/components/parameters/X-Auth-Token'
        - $ref: '#/components/parameters/x-2fa-code'
        - $ref: '#/components/parameters/X-2fa-method'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  description: The value to update the setting.
                color:
                  type: string
                  description: The color code to update the setting.
                editor:
                  type: string
                  description: 'The editor key, with color value. Required, if color was set.'
                execute:
                  type: boolean
                  description: To trigger a action-button.
              required:
                - value
    get:
      summary: Get Setting
      tags:
        - Custom
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/SettingBoolean'
                  - $ref: '#/components/schemas/SettingInteger'
                  - $ref: '#/components/schemas/SettingString'
                  - $ref: '#/components/schemas/SettingArray'
                  - $ref: '#/components/schemas/SettingObject'
              examples:
                Success Example:
                  value:
                    _id: Livechat_enabled
                    value: false
                    success: true
        '401':
          $ref: '#/components/responses/authorizationError'
      operationId: get-api-v1-settings-_id
      description: |-
        Get details of a setting by ID.
        Permission required: `view-privileged-setting`
        ### Changelog
        | Version      | Description |
        | ---------------- | ------------|
        |0.42.0            | Added       |
      parameters:
        - $ref: '#/components/parameters/X-User-Id'
        - $ref: '#/components/parameters/X-Auth-Token'
components:
  schemas:
    SettingInteger:
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          properties:
            success:
              type: boolean
            value:
              type: integer
    SettingString:
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          properties:
            success:
              type: boolean
            value:
              type: string
    SettingBoolean:
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          properties:
            success:
              type: boolean
            value:
              type: boolean
    SettingArray:
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          properties:
            success:
              type: boolean
            value:
              type: array
    SettingObject:
      allOf:
        - $ref: '#/components/schemas/Setting'
        - type: object
          properties:
            success:
              type: boolean
            value:
              type: object
    Setting:
      type: object
      properties:
        _id:
          type: string
  parameters:
    Auth-Token:
      name: X-Auth-Token
      in: header
      description: The `authToken` of the authenticated user.
      required: true
      schema:
        type: string
      example: RScctEHSmLGZGywfIhWyRpyofhKOiMoUIpimhvheU3f
    UserId:
      name: X-User-Id
      in: header
      description: The `userId` of the authenticated user.
      required: true
      schema:
        type: string
      example: rbAXPnMktTFbNpwtJ
    X-User-Id:
      name: X-User-Id
      in: header
      required: true
      schema:
        type: string
      example: CkCPNctrgCDfmWLqC
      description: The user ID.
    X-Auth-Token:
      name: X-Auth-Token
      in: header
      required: true
      schema:
        type: string
      example: 1Dd4iN_ClKn5jl-xPC36snQ4s9Zd5GZnXCQuCNSKcVE
      description: The authentication token.
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
      example: 50
      description: 'Number of items to "skip" in the query, i.e. requests return count items, skipping the first offset items.'
    count:
      name: count
      in: query
      required: false
      schema:
        type: integer
      example: 50
      description: How many items to return.
    sort:
      name: sort
      in: query
      required: false
      schema: { }
      description: 'List of fields to order by, and in which direction. This is a JSON object, with properties listed in desired order, with values of 1 for ascending, or -1 for descending. For example, {"value": -1, "_id": 1}'
    fields:
      name: fields
      in: query
      required: false
      schema: { }
      description: 'This parameter accepts a JSON object with properties that have a value of 1 or 0 to include or exclude them in the response. For example, to only retrieve the usernames of users: fields={ "username": 1 }'
    x-2fa-code:
      name: X-2fa-Code
      in: header
      required: true
      schema:
        type: string
      description: 'The 2FA code from the authentication method. If the method is password, encrypt it as SHA256.'
    X-2fa-method:
      name: X-2fa-method
      in: header
      required: true
      schema:
        type: string
      description: 'The desired method to get the 2FA code. It can be `email`, `totp`, or `password`.'
  responses:
    trueSuccess:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
          examples:
            Success:
              value:
                success: true
    authorizationError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
          examples:
            Authorization Error:
              value:
                status: error
                message: You must be logged in to do this.

